/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AllRouteImport } from './routes/all'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalcSlugRouteImport } from './routes/calc.$slug'
import { Route as CCategoryRouteImport } from './routes/c.$category'

const AllRoute = AllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalcSlugRoute = CalcSlugRouteImport.update({
  id: '/calc/$slug',
  path: '/calc/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CCategoryRoute = CCategoryRouteImport.update({
  id: '/c/$category',
  path: '/c/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/all': typeof AllRoute
  '/c/$category': typeof CCategoryRoute
  '/calc/$slug': typeof CalcSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/all': typeof AllRoute
  '/c/$category': typeof CCategoryRoute
  '/calc/$slug': typeof CalcSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/all': typeof AllRoute
  '/c/$category': typeof CCategoryRoute
  '/calc/$slug': typeof CalcSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/all' | '/c/$category' | '/calc/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/all' | '/c/$category' | '/calc/$slug'
  id: '__root__' | '/' | '/all' | '/c/$category' | '/calc/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllRoute: typeof AllRoute
  CCategoryRoute: typeof CCategoryRoute
  CalcSlugRoute: typeof CalcSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/all': {
      id: '/all'
      path: '/all'
      fullPath: '/all'
      preLoaderRoute: typeof AllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calc/$slug': {
      id: '/calc/$slug'
      path: '/calc/$slug'
      fullPath: '/calc/$slug'
      preLoaderRoute: typeof CalcSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$category': {
      id: '/c/$category'
      path: '/c/$category'
      fullPath: '/c/$category'
      preLoaderRoute: typeof CCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllRoute: AllRoute,
  CCategoryRoute: CCategoryRoute,
  CalcSlugRoute: CalcSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
